### PR TITLE
0.2.2

### PR DESCRIPTION
**Pull request by PierreMartinon**
Updated CTBase and CTProblems
All problems pass except simple exponential - conso min that seems horribly wrong.
Can you check this one then do the PR ?
Thanks

### CODE REVIEW

**Comment by ocots** [comment]
Indeed, you obtain a negative value for the objective which seems weird: 

https://github.com/control-toolbox/CTDirect.jl/actions/runs/4621377560/jobs/8172726310?pr=34#step:5:1147

**Comment by ocots** [comment]
We could plot both solutions, from CTProblems and CTDirect.

**Comment by ocots** [comment]
We get

Capture d’écran 2023-04-05 à 21 35 58

Capture d’écran 2023-04-05 à 21 36 05

**Comment by PierreMartinon** [comment]
> Indeed, you obtain a negative value for the objective which seems weird:

Yup. I'll have a look at the problem today and do some manual tests. I suspect there is a constraint missing somewhere, which allows the direct method to do some weird stuff :D

**Comment by ocots** [comment]
I think it is not to CTProblems to smooth it. But we could add a tag to tell that the solution is not smooth.

You can do 
```julia
if :consumption in description
   # smooth it
end
```

**Comment by PierreMartinon** [comment]
I'll see what I can do

**Comment by joseph-gergaud** [comment]
For the problem, when you use the contraint on the control : 0<=u<=1 did you put u and not |u| for the Lagrangian cost ?

I think that if we don't use the Mayer transformation for this problem. We'll converge with ipopt because he use log barrier .

**Comment by PierreMartinon** [comment]
> For the problem, when you use the contraint on the control : 0<=u<=1 did you put u and not |u| for the Lagrangian cost ?

No I kept the original cost abs(u).
 
> I think that if we don't use the Mayer transformation for this problem. We'll converge with ipopt because he use log barrier .

Could be worth a try. Add an issue to implement the Mayer cost ?

By the way, the problem fails on bocop3 as well. It's just a crappy example :D

**Comment by joseph-gergaud** [comment]
For phis problem we can try to optimize
```math
\int_0^1 |u(t)| + \varepsilon(\log(|u(t)|)+\log(1-|u(t)|))dt
```

witch is smooth and we should converge

**Pull request merged**
