### PR TITLE
Added explicit time grid as optional parameter; compatible with free times

### PR DESCRIPTION
**Pull request by PierreMartinon**
- **time_grid** added as an optional argument to *solve* (and *directTranscription*)
- **time_grid** overrides **grid_size**
- grid can be non-uniform but must be strictly increasing (will throw ArgumentError otherwise)
- grid should be normalized (ie in [0,1]) and will be normalized automatically if needed. The use of a normalized grid internally is due to the handling of the free times cases (t0 and/or tf).
- note that there is currently no consistency check between the given grid and fixed t0/tf.
- grid is currently not typed but should be consistent with *CTBase.TimeDisc*
Syntax examples
```
solve(ocp, time_grid=LinRange(0,1,101)) # equivalent to default discretization ie N=100
solve(ocp, time_grid=[0,0.3,1,1.9,2])
``` 
Plot: non-uniform grid with fixed times [0,2] and free t0 and tf
fig1
Plot: non-uniform grid with free t0 and tf
fig2

@ocots @jbcaillau For the future I would like to fuse **time_grid** and **grid_size** into a single argument, since the two are kind of mutually exclusive. We could call it **time_disc** and it would be an union of grid size and time grid (ie either an integer or a vector, to simplify).

Thoughts ?

### CODE REVIEW

**Comment by ocots** [comment]
For the consistency I had written in `CTDirectShooting`:

```julia
function check_grid_validity(t0::Time, tf::Time, T::TimesDisc)
    # T: t0 ≤ t1 ≤ ... ≤ tf
    valid = true
    valid = (t0==T[1]) & valid
    valid = (tf==T[end]) & valid
    valid = (T==sort(T)) & valid
    return valid
end

function check_grid_validity(U::Vector{<:MyVector}, T::TimesDisc)
    return length(U) == (length(T) - 1) || length(U) == length(T)
end
```

**Comment by jbcaillau** [comment]
@PierreMartinon I like it better to keep different named arguments (more user friendly), provided there is a consistency check. Would be nice to check what the current standard in Julia is.

> @ocots @jbcaillau For the future I would like to fuse **time_grid** and **grid_size** into a single argument, since the two are kind of mutually exclusive. We could call it **time_disc** and it would be an union of grid size and time grid (ie either an integer or a vector, to simplify).
> 
> Thoughts ?

**Comment by PierreMartinon** [comment]
> @PierreMartinon I like it better to keep different named arguments (more user friendly), provided there is a consistency check. Would be nice to check what the current standard in Julia is.
> 
> > @ocots @jbcaillau For the future I would like to fuse **time_grid** and **grid_size** into a single argument, since the two are kind of mutually exclusive. We could call it **time_disc** and it would be an union of grid size and time grid (ie either an integer or a vector, to simplify).
> > Thoughts ?

Ok, let's keep both then.

**Comment by PierreMartinon** [comment]
> For the consistency I had written in `CTDirectShooting`:
> 
> ```julia
> function check_grid_validity(t0::Time, tf::Time, T::TimesDisc)
>     # T: t0 ≤ t1 ≤ ... ≤ tf
>     valid = true
>     valid = (t0==T[1])   && valid
>     valid = (tf==T[end]) && valid
>     valid = (T==sort(T)) && valid
>     return valid
> end
> 
> function check_grid_validity(U::Vector{<:MyVector}, T::TimesDisc)
>     return length(U) == (length(T) - 1) || length(U) == length(T)
> end
> ```

Hey, the first one looks interesting for me :)
For the sorted part I would suggest to use something like
```
if !issorted(time_grid,lt=<=)
   throw(ArgumentError("given time grid is not strictly increasing. Aborting..."))
```
since it seems that the check T==sort(T) actually returns true if there are duplicate values, which for us is not acceptable. We have to specify the <= comparison operator (instead of the default <) to reject equal values, which I find rather counter intuitive. I believe you can pass it to *sort* too, but since *issorted* exists, we may as well use it ?

**Pull request merged**
