### PR TITLE
WIP: separate function for direct transcription (ocp to nlp)

### PR DESCRIPTION
**Pull request by PierreMartinon**
TODO:
- [x] add an export of the NLP problem alone i.e the member docp.nlp (note that we then lose the link to the original OCP, in terms of initial guess and solution)
```
docp = DirectTranscription(ocp1, grid_size=100, init=init_constant)
nlp = getNLP(docp)
print(docp.nlp.meta.x0)
```

- [x] add possibility to pass initial guess to solveDOCP (currently passed to DirectTrancription since initial guess is part of NLPModel). Using for instance a previous solution to generate the initial guess
```
init_sol = OptimalControlInit(sol)
```
one can then set the initial guess in the DOCP
```
setDOCPInit(docp, init_sol)
sol = solveDOCP(docp, print_level=5, tol=1e-12)
```
or pass it to the solver call (will bypass the initial guess stored in docp)
```
sol = solveDOCP(docp, init=init_sol, print_level=5, tol=1e-12)
```

Note: some indicators currently defined in DOCP could be migrated up to the OCP, such as has_free_final_time, has_variable etc, similarly to the existing is_min(). Using these higher level functions is probably cleaner than looking at the internal members of OCP.

### CODE REVIEW

**Comment by jbcaillau** [comment]
@PierreMartinon @tmigot linked to [this issue](https://github.com/control-toolbox/CTDirect.jl/issues/70)

**Comment by tmigot** [comment]
@PierreMartinon I am just reading the comments, so I am not sure what was blocking, but it is possible to broadcast an initial guess to ADNLPModel to change the initial guess, i.e., something like
```
nlp = ADNLPModel(...)
nlp.meta.x0 .= ones(n)
```
or the alternative is to pass an initial guess directly to the solver (it takes nlp.meta.x0 only by default).

**Comment by PierreMartinon** [comment]
Thanks @tmigot for the clarification ! I guess people usually prefer to pass the initial guess to the solver directly. Both options added.

**Comment by jbcaillau** [comment]
thanks @tmigot ; @PierreMartinon please send a message when PR is ready to merge 🤞🏾

**Comment by PierreMartinon** [comment]
Ok for me, @joseph-gergaud do you have more changes before the merge ?

**Pull request merged**
