### PR TITLE
crude example of basic grid refinement

### PR DESCRIPTION
**Pull request by PierreMartinon**
@joseph-gergaud To illustrate the possibility of a grid refinement algorithm, we do a discrete continuation on the discretization steps. We use limited iterations until we reach the desired steps, then do a final solve. Apparently this can be faster than than directlty solving the problem.

NB. In this example we only used uniform grids so we could just have passe *grid_size* instead of *time_grid*, but the point of grid refinement would to use non-uniform grids.

```
julia> include("test/test_grid.jl")
Test: grid options

Basic solve
steps  250, objective  1.012576, iterations   46
 15.297255 seconds (41.06 M allocations: 5.121 GiB, 1.38% gc time, 1.55% compilation time)

Step continuation
steps   10, objective  1.000258, iterations set to    5
steps   20, objective  1.004950, iterations set to    5
steps   40, objective  1.009693, iterations set to    5
steps   80, objective  1.012172, iterations set to    5
steps  160, objective  1.012389, iterations set to    5
steps  250, objective  1.011619, iterations set to    5
steps  250, objective  1.012576, iterations   14
  9.759167 seconds (21.74 M allocations: 2.728 GiB, 7.79% gc time)

```

### CODE REVIEW

**Comment by ocots** [comment]
I am about to add an application. I do a refinement to increase the speed of convergence. See [here](https://github.com/control-toolbox/OptimalControl.jl/blob/204-add-mri-saturation-problem-example/docs/src/application-mri-saturation.md#direct-method).

**Comment by PierreMartinon** [comment]
Tests with goddard (free tf, max rf, v constraint) are not great, and very sensitive to the bounds on the Dt_i.
control_goddard_bad
control_goddard

Maybe the optimization finds 'bad' values for the time steps so it can cheat the ODE and get a better objective...
Also, there may be a derivatives problem for the external function dt.

This variable grid feature needs a proper implementation if we want to do more serious testing.

**Comment by ocots** [comment]
I agree.

**Comment by PierreMartinon** [comment]
For the syntax, maybe we can reuse the existing arguments with something like
```solve(ocp, grid_size=N, time_grid=:optimized)```

**Pull request merged**
